AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  PoC for State Machine Map

Resources:
  GreetingsMapperStateMachine:
    Type: AWS::Serverless::StateMachine # More info about State Machine Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-statemachine.html
    Properties:
      DefinitionUri: statemachine/mapper.asl.json
      DefinitionSubstitutions:
        HelloHandlerArn: !GetAtt HelloHandler.Arn
      Policies: # Find out more about SAM policy templates: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-policy-templates.html
        - LambdaInvokePolicy:
            FunctionName: !Ref HelloHandler

  HelloHandler:
    Type: AWS::Serverless::Function # More info about Function Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html
    Properties:
      CodeUri: functions/hello-handler/
      Handler: app.helloHandler
      Runtime: nodejs14.x
      Architectures:
        - x86_64

Outputs:
  # StockTradingStateMachineHourlyTradingSchedule is an implicit Schedule event rule created out of Events key under Serverless::StateMachine
  # Find out more about other implicit resources you can reference within SAM
  # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-specification-generated-resources.html
  GreetingsMapperStateMachineArn:
    Description: "Stock Trading state machine ARN"
    Value: !Ref GreetingsMapperStateMachine
  GreetingsMapperStateMachineRole:
    Description: "IAM Role created for Greetings Mapper state machine based on the specified SAM Policy Templates"
    Value: !GetAtt GreetingsMapperStateMachine.Arn
